### ISSUE TITLE
Error in test_init

### ISSUE THREAD

**Issue by pradal** [GeraultTr/Root_BRIDGES#2]
After installation I solved two errors:

- __init__.py file missing in log package (see issue https://github.com/GeraultTr/log/issues/2 )
- I install trimesh which was missing in my env (perhaps this is my fault because some deps were not found on Mac)

Now the error is
```python
test_init.py:6: in <module>
    test_init()
test_init.py:4: in test_init
    model = Model(time_step=3600)
../root_bridges/root_bridges.py:46: in __init__
    parameters = scenario["parameters"]["root_bridges"]
E   KeyError: 'parameters'

```
I want to have everything working before benchmarking...

**Comment by GeraultTr** [comment]
- Thank you for the __init__, I double checked it on every other packages.
- For dependancies this is on me, trimesh was a recent addition to visualize the CN-Wheat shoot, which is of no use for us here, but it made the logger requiring it and I forgot to add it to the requirements.
- For the test, I updated it, it didn't receive any input scenario, so the error was expected. Does 15f2393 resolve the issue?
